// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxu0gt-YpCCmq5FhvfveMkAK80PfULZSY',
    appId: '1:841575265745:web:ff7a381b3757c8f1901cf0',
    messagingSenderId: '841575265745',
    projectId: 'database-unicah-34d91',
    authDomain: 'database-unicah-34d91.firebaseapp.com',
    storageBucket: 'database-unicah-34d91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcAfzHoUpUzWJ3V0_qLuBSX4MyjcUstGk',
    appId: '1:841575265745:android:fd799b3e022fc653901cf0',
    messagingSenderId: '841575265745',
    projectId: 'database-unicah-34d91',
    storageBucket: 'database-unicah-34d91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_70bVEoGTf_fbgEMZzjNv9cEaLC8bdZI',
    appId: '1:841575265745:ios:259c27a069b269b2901cf0',
    messagingSenderId: '841575265745',
    projectId: 'database-unicah-34d91',
    storageBucket: 'database-unicah-34d91.firebasestorage.app',
    iosBundleId: 'com.example.appDatabaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_70bVEoGTf_fbgEMZzjNv9cEaLC8bdZI',
    appId: '1:841575265745:ios:259c27a069b269b2901cf0',
    messagingSenderId: '841575265745',
    projectId: 'database-unicah-34d91',
    storageBucket: 'database-unicah-34d91.firebasestorage.app',
    iosBundleId: 'com.example.appDatabaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxu0gt-YpCCmq5FhvfveMkAK80PfULZSY',
    appId: '1:841575265745:web:dc77222678ccf40b901cf0',
    messagingSenderId: '841575265745',
    projectId: 'database-unicah-34d91',
    authDomain: 'database-unicah-34d91.firebaseapp.com',
    storageBucket: 'database-unicah-34d91.firebasestorage.app',
  );

}